/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author Arell
 */
public class DatosFinales extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPaciente
     */
    public DatosFinales() {
        initComponents();
        this.setTitle("Registro Paciente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        Iniciar_Sesion = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JPanel();
        Hospital_General = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        CampoUsuario1 = new javax.swing.JTextField();
        CampoUsuario2 = new javax.swing.JTextField();
        Usuario2 = new javax.swing.JLabel();
        CampoUsuario3 = new javax.swing.JTextField();
        Usuario3 = new javax.swing.JLabel();
        Usuario4 = new javax.swing.JLabel();
        CampoUsuario4 = new javax.swing.JTextField();
        Usuario5 = new javax.swing.JLabel();
        CampoUsuario5 = new javax.swing.JTextField();
        Usuario7 = new javax.swing.JLabel();
        CampoUsuario6 = new javax.swing.JTextField();
        Usuario6 = new javax.swing.JLabel();
        CampoUsuario7 = new javax.swing.JTextField();
        Usuario8 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        Usuario1 = new javax.swing.JLabel();
        btnAceptar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iniciar_Sesion.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        Iniciar_Sesion.setText("Datos-Finales");
        FondoPanel.add(Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        FondoAzul.setBackground(new java.awt.Color(0, 153, 255));
        FondoAzul.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Hospital_General.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        Hospital_General.setText("Hospital General");

        javax.swing.GroupLayout FondoAzulLayout = new javax.swing.GroupLayout(FondoAzul);
        FondoAzul.setLayout(FondoAzulLayout);
        FondoAzulLayout.setHorizontalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hospital_General, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoAzulLayout.setVerticalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoAzulLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Hospital_General, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FondoPanel.add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        CampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuarioActionPerformed(evt);
            }
        });
        FondoPanel.add(CampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, -1));

        Usuario.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario.setText("Nombres");
        FondoPanel.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        CampoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuario1ActionPerformed(evt);
            }
        });
        FondoPanel.add(CampoUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));
        FondoPanel.add(CampoUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 170, -1));

        Usuario2.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario2.setText("Fecha");
        FondoPanel.add(Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        FondoPanel.add(CampoUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, -1));

        Usuario3.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario3.setText("CURP");
        FondoPanel.add(Usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        Usuario4.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario4.setText("Apellidos");
        FondoPanel.add(Usuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        FondoPanel.add(CampoUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 170, -1));

        Usuario5.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario5.setText("Direccion");
        FondoPanel.add(Usuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        FondoPanel.add(CampoUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 170, -1));

        Usuario7.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario7.setText("No. Casa");
        FondoPanel.add(Usuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        FondoPanel.add(CampoUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 170, -1));

        Usuario6.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario6.setText("Telefono");
        FondoPanel.add(Usuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, -1));
        FondoPanel.add(CampoUsuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 170, -1));

        Usuario8.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario8.setText("No. Seguro Social");
        FondoPanel.add(Usuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Editar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        FondoPanel.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 310, 30));

        jCheckBox1.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jCheckBox1.setText("Masculino");
        FondoPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jCheckBox2.setText("Femenino");
        FondoPanel.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        Usuario1.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario1.setText("Genero");
        FondoPanel.add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        btnAceptar1.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar1.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        btnAceptar1.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar1.setText("Aceptar");
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });
        FondoPanel.add(btnAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void CampoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuario1ActionPerformed

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    private void CampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosFinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosFinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosFinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosFinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosFinales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JTextField CampoUsuario1;
    private javax.swing.JTextField CampoUsuario2;
    private javax.swing.JTextField CampoUsuario3;
    private javax.swing.JTextField CampoUsuario4;
    private javax.swing.JTextField CampoUsuario5;
    private javax.swing.JTextField CampoUsuario6;
    private javax.swing.JTextField CampoUsuario7;
    private javax.swing.JPanel FondoAzul;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel Hospital_General;
    private javax.swing.JLabel Iniciar_Sesion;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario2;
    private javax.swing.JLabel Usuario3;
    private javax.swing.JLabel Usuario4;
    private javax.swing.JLabel Usuario5;
    private javax.swing.JLabel Usuario6;
    private javax.swing.JLabel Usuario7;
    private javax.swing.JLabel Usuario8;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    // End of variables declaration//GEN-END:variables
}
