/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author Arell
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
         initComponents();
        this.setTitle("Registro Medicos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        Iniciar_Sesion = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JPanel();
        Hospital_General = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        Usuario2 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        Usuario3 = new javax.swing.JLabel();
        FondoGenero = new javax.swing.JPanel();
        Usuario1 = new javax.swing.JLabel();
        SelectMan = new javax.swing.JCheckBox();
        SelectWomen = new javax.swing.JCheckBox();
        Usuario4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        Usuario5 = new javax.swing.JLabel();
        txtNoCase = new javax.swing.JTextField();
        Usuario7 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        Usuario6 = new javax.swing.JLabel();
        txtSeguro = new javax.swing.JTextField();
        Usuario8 = new javax.swing.JLabel();
        CampoUsuario8 = new javax.swing.JTextField();
        Usuario9 = new javax.swing.JLabel();
        CampoUsuario9 = new javax.swing.JTextField();
        Usuario10 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iniciar_Sesion.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        Iniciar_Sesion.setText("Registro-Medico");
        FondoPanel.add(Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        FondoAzul.setBackground(new java.awt.Color(0, 153, 255));
        FondoAzul.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Hospital_General.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        Hospital_General.setText("Hospital General");

        javax.swing.GroupLayout FondoAzulLayout = new javax.swing.GroupLayout(FondoAzul);
        FondoAzul.setLayout(FondoAzulLayout);
        FondoAzulLayout.setHorizontalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hospital_General, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(516, Short.MAX_VALUE))
        );
        FondoAzulLayout.setVerticalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoAzulLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Hospital_General, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FondoPanel.add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 40));
        FondoPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, -1));

        Usuario.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario.setText("Nombres");
        FondoPanel.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        FondoPanel.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
        FondoPanel.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 150, -1));

        Usuario2.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario2.setText("Fecha");
        FondoPanel.add(Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));
        FondoPanel.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        Usuario3.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario3.setText("CURP");
        FondoPanel.add(Usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        FondoGenero.setBackground(new java.awt.Color(255, 255, 255));
        FondoGenero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Usuario1.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario1.setText("Genero");

        SelectMan.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        SelectMan.setText("Masculino");

        SelectWomen.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        SelectWomen.setText("Femenino");

        javax.swing.GroupLayout FondoGeneroLayout = new javax.swing.GroupLayout(FondoGenero);
        FondoGenero.setLayout(FondoGeneroLayout);
        FondoGeneroLayout.setHorizontalGroup(
            FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGeneroLayout.createSequentialGroup()
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoGeneroLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(SelectMan)
                        .addGap(34, 34, 34)
                        .addComponent(SelectWomen))
                    .addGroup(FondoGeneroLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Usuario1)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        FondoGeneroLayout.setVerticalGroup(
            FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGeneroLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Usuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectMan)
                    .addComponent(SelectWomen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FondoPanel.add(FondoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 230, 70));

        Usuario4.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario4.setText("Apellidos");
        FondoPanel.add(Usuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));
        FondoPanel.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        Usuario5.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario5.setText("Direccion");
        FondoPanel.add(Usuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        FondoPanel.add(txtNoCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 180, -1));

        Usuario7.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario7.setText("No. Casa");
        FondoPanel.add(Usuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));
        FondoPanel.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 230, -1));

        Usuario6.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario6.setText("Telefono");
        FondoPanel.add(Usuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 70, -1));
        FondoPanel.add(txtSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, -1));

        Usuario8.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario8.setText("No. Seguro Social");
        FondoPanel.add(Usuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));
        FondoPanel.add(CampoUsuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 230, -1));

        Usuario9.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario9.setText("Cedúla Profesional");
        FondoPanel.add(Usuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, -1));
        FondoPanel.add(CampoUsuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 180, -1));

        Usuario10.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Usuario10.setText("Vigencia");
        FondoPanel.add(Usuario10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        FondoPanel.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoUsuario8;
    private javax.swing.JTextField CampoUsuario9;
    private javax.swing.JPanel FondoAzul;
    private javax.swing.JPanel FondoGenero;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel Hospital_General;
    private javax.swing.JLabel Iniciar_Sesion;
    private javax.swing.JCheckBox SelectMan;
    private javax.swing.JCheckBox SelectWomen;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario10;
    private javax.swing.JLabel Usuario2;
    private javax.swing.JLabel Usuario3;
    private javax.swing.JLabel Usuario4;
    private javax.swing.JLabel Usuario5;
    private javax.swing.JLabel Usuario6;
    private javax.swing.JLabel Usuario7;
    private javax.swing.JLabel Usuario8;
    private javax.swing.JLabel Usuario9;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoCase;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSeguro;
    // End of variables declaration//GEN-END:variables
}
